//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArctisBatteryMonitor.Resources.Localization {


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArctisBatteryMonitor.Resources.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        // Menu

        internal static string MenuReconnect {
            get {
                return ResourceManager.GetString("MenuReconnect", resourceCulture);
            }
        }

        internal static string MenuSelectHeadset {
            get {
                return ResourceManager.GetString("MenuSelectHeadset", resourceCulture);
            }
        }

        internal static string NoDeviceFound {
            get {
                return ResourceManager.GetString("NoDeviceFound", resourceCulture);
            }
        }

        internal static string MenuNotifications {
            get {
                return ResourceManager.GetString("MenuNotifications", resourceCulture);
            }
        }

        internal static string MenuNotifConnected {
            get {
                return ResourceManager.GetString("MenuNotifConnected", resourceCulture);
            }
        }

        internal static string MenuNotifDisconnected {
            get {
                return ResourceManager.GetString("MenuNotifDisconnected", resourceCulture);
            }
        }

        internal static string MenuNotifEnableAll {
            get {
                return ResourceManager.GetString("MenuNotifEnableAll", resourceCulture);
            }
        }

        internal static string MenuLanguage {
            get {
                return ResourceManager.GetString("MenuLanguage", resourceCulture);
            }
        }

        internal static string MenuLanguageSystem {
            get {
                return ResourceManager.GetString("MenuLanguageSystem", resourceCulture);
            }
        }

        internal static string MenuStartWithWindows {
            get {
                return ResourceManager.GetString("MenuStartWithWindows", resourceCulture);
            }
        }

        internal static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }

        // Notifications

        internal static string NotifNoDeviceTitle {
            get {
                return ResourceManager.GetString("NotifNoDeviceTitle", resourceCulture);
            }
        }

        internal static string NotifNoDeviceMessage {
            get {
                return ResourceManager.GetString("NotifNoDeviceMessage", resourceCulture);
            }
        }

        internal static string NotifMultipleTitle {
            get {
                return ResourceManager.GetString("NotifMultipleTitle", resourceCulture);
            }
        }

        internal static string NotifMultipleMessage {
            get {
                return ResourceManager.GetString("NotifMultipleMessage", resourceCulture);
            }
        }

        internal static string NotifConnectedTitle {
            get {
                return ResourceManager.GetString("NotifConnectedTitle", resourceCulture);
            }
        }

        internal static string NotifDisconnectedTitle {
            get {
                return ResourceManager.GetString("NotifDisconnectedTitle", resourceCulture);
            }
        }
    }
}
